/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package schema;


import org.apache.avro.specific.AvroGenerated;
import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@AvroGenerated
public class Cloud extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -645316961180767521L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Cloud\",\"namespace\":\"com.zliu.schema\",\"fields\":[{\"name\":\"all\",\"type\":\"double\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public double all;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Cloud() {}

  /**
   * All-args constructor.
   * @param all The new value for all
   */
  public Cloud(Double all) {
    this.all = all;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public Object get(int field$) {
    switch (field$) {
    case 0: return all;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: all = (Double)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'all' field.
   * @return The value of the 'all' field.
   */
  public Double getAll() {
    return all;
  }

  /**
   * Sets the value of the 'all' field.
   * @param value the value to set.
   */
  public void setAll(Double value) {
    this.all = value;
  }

  /**
   * Creates a new Cloud RecordBuilder.
   * @return A new Cloud RecordBuilder
   */
  public static Builder newBuilder() {
    return new Builder();
  }

  /**
   * Creates a new Cloud RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Cloud RecordBuilder
   */
  public static Builder newBuilder(Builder other) {
    return new Builder(other);
  }

  /**
   * Creates a new Cloud RecordBuilder by copying an existing Cloud instance.
   * @param other The existing instance to copy.
   * @return A new Cloud RecordBuilder
   */
  public static Builder newBuilder(Cloud other) {
    return new Builder(other);
  }

  /**
   * RecordBuilder for Cloud instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Cloud>
    implements org.apache.avro.data.RecordBuilder<Cloud> {

    private double all;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.all)) {
        this.all = data().deepCopy(fields()[0].schema(), other.all);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Cloud instance
     * @param other The existing instance to copy.
     */
    private Builder(Cloud other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.all)) {
        this.all = data().deepCopy(fields()[0].schema(), other.all);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'all' field.
      * @return The value.
      */
    public Double getAll() {
      return all;
    }

    /**
      * Sets the value of the 'all' field.
      * @param value The value of 'all'.
      * @return This builder.
      */
    public Builder setAll(double value) {
      validate(fields()[0], value);
      this.all = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'all' field has been set.
      * @return True if the 'all' field has been set, false otherwise.
      */
    public boolean hasAll() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'all' field.
      * @return This builder.
      */
    public Builder clearAll() {
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public Cloud build() {
      try {
        Cloud record = new Cloud();
        record.all = fieldSetFlags()[0] ? this.all : (Double) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
